repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: check-yaml
      exclude: "^charts/cf-common-tests/tempaltes/*"
    - id: end-of-file-fixer
      exclude: &exclude_pattern 'README.md'
    - id: trailing-whitespace
