libraryMode: false

global: {}

controller:
  enabled: true
  type: deployment
  replicas: 1
  deployment:
    strategy: Recreate

container:
  image:
    registry: docker.io
    repository: gogost/gost
    tag: latest
    pullPolicy: IfNotPresent
  command:
    - "gost"
  args:
    - "-L"
    - 'rtcp://:0//internal-gateway:80'
    - "-F"
    - "tunnel+wss://$(GOST_SERVER_HOSTNAME):443?tunnel.id=$(GOST_PLATFORM_TUNNEL_ID)&keepalive=true&ttl=15s"
  env:
    GOST_SERVER_HOSTNAME: ""
    GOST_PLATFORM_TUNNEL_ID: ""
    GOST_PLATFORM_TUNNEL_HOSTNAME: ""
  probes:
    liveness:
      enabled: true
      type: exec
      exec:
        command:
          - wget
          - --server-response
          - --spider
          - https://$(GOST_PLATFORM_TUNNEL_HOSTNAME)
      spec:
        initialDelaySeconds: 30
        periodSeconds: 15
        timeoutSeconds: 15
        successThreshold: 1
        failureThreshold: 2

nodeSelector: {}
tolerations: []
affinity: {}
hpa: {}
keda:
  spec: {}
  auth: {}
pdb: {}
