codefresh:
  serviceEndpoints:
    cfapi-endpoints:
      svc: cfapi-endpoints
      port: 80
    cfapi-environments:
      svc: cfapi-environments
      port: 80
    cfapi-downloadlogmanager:
      svc: cfapi-downloadlogmanager
      port: 80
    cfapi-gitops-resource-receiver:
      svc: cfapi-gitops-resource-receiver
      port: 80
    cfapi-test-reporting:
      svc: cfapi-test-reporting
      port: 80
    cfapi-kubernetesresourcemonitor:
      svc: cfapi-kubernetesresourcemonitor
      port: 80
    cfapi-kubernetes-endpoints:
      svc: cfapi-kubernetes-endpoints
      port: 80
    cfapi-admin:
      svc: cfapi-admin
      port: 80
    cfapi-teams:
      svc: cfapi-teams
      port: 80
    cfapi-ws:
      svc: cfapi-ws
      port: 80
    cfui:
      svc: cfui
      port: 80
    argo-platform-api-graphql:
      svc: argo-platform-api-graphql
      port: 80
    argo-platform-api-events:
      svc: argo-platform-api-events
      port: 80
    argo-platform-ui: 
      svc: argo-platform-ui
      port: 4200
    argo-hub:
      svc: argo-hub-platform
      port: 80
    nomios:
      svc: nomios
      port: 80
    jira-addon:
      svc: cf-jira-addon
      port: 9000

nginx:
  config:
    # -- Defines the number of worker processes.
    workerProcesses: "8"
    # -- Sets the maximum number of simultaneous connections that can be opened by a worker process.
    workerConnections: "16384"
    # -- Changes the limit on the largest size of a core file (RLIMIT_CORE) for worker processes. Used to increase the limit without restarting the main process.
    workerRlimitNofile: "1047552"
    # -- Enable logging of 2xx and 3xx HTTP requests
    verboseLogging: false
    # -- NGINX log format
    logFormat: |-
      main escape=json '{ "time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x-forward-for": "$proxy_add_x_forwarded_for", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time, "method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent", "http_x_github_delivery": "$http_x_github_delivery", "http_x_hook_uuid": "$http_x_hook_uuid", "metadata": { "correlationId": "$request_id", "service": "ingress", "time": "$time_iso8601" } }';
    # E.g.
    # logFormat: |-
    #   main '$remote_addr - $remote_user [$time_local]  $status '
    #           '"$request" $body_bytes_sent "$http_referer" '
    #           '"$http_user_agent" "$http_x_forwarded_for"';
    # -- Sets the log level of the NGINX error log. One of `debug`, `info`, `notice`, `warn`, `error`, `crit`, `alert`, or `emerg`
    errorLogLevel: error
    # -- Enables NGINX access logs
    accessLogEnabled: true
    # -- Allows appending custom configuration to the server block (string)
    serverSnippet: ""
    # -- Allows appending custom directives to the server block (map)
    serverDirectives: {}
    # -- Allows appending custom configuration to the http block (string)
    httpSnippet: ""
    # -- Allows appending custom directives to the http block (map)
    httpDirectives: {}
    # -- Allows appending custom configuration to the location blocks (string)
    locationSnippet: |
      proxy_http_version 1.1;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Request-ID $request_id;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Original-URI $request_uri;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    # -- Allows appending custom directives to the location blocks (map)
    locationDirectives:
      proxy_buffer_size: "64k"
      proxy_buffers: "4 64k"
      client_max_body_size: "5M"
      client_body_buffer_size: "16k"
      proxy_connect_timeout: "5s"
      proxy_send_timeout: "60s"
      proxy_read_timeout: "60s"

    # -- Allows to set a custom resolver
    resolver: null

    # -- Config file contents for Nginx. Passed through the `tpl` function to allow templating.
    # !! Moved into separate template at `templates/nginx/configmap.yaml`
    # @default -- See below
    file: ""

    locations:
      /api/auth/authenticate:
        proxy:
          proxyPassSnippet: |
            proxy_pass_request_body off;
        locationSnippet: |
          proxy_set_header Content-Length "";
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Original-URI $request_uri;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        locationDirectives:
      