# Defines if library mode is used for tunnel client. No templates are generated when using this mode.
# Added to support usage in Codefresh On-Premise Helm chart
libraryMode: false

# -- Codefresh platform settings
# @default -- See below
codefresh:
  url: "g.codefresh.io"

  cfapi-endpoints-svc: cfapi-endpoints
  cfapi-endpoints-port: 80

  cfapi-environments-svc: cfapi-environments
  cfapi-environments-port: 80

  cfapi-downloadlogmanager-svc: cfapi-downloadlogmanager
  cfapi-downloadlogmanager-port: 80

  cfapi-gitops-resource-receiver-svc: cfapi-gitops-resource-receiver
  cfapi-gitops-resource-receiver-port: 80

  cfapi-test-reporting-svc: cfapi-test-reporting
  cfapi-test-reporting-port: 80

  cfapi-kubernetesresourcemonitor-svc: cfapi-kubernetesresourcemonitor
  cfapi-kubernetesresourcemonitor-port: 80

  cfapi-kubernetes-endpoints-svc: cfapi-kubernetes-endpoints
  cfapi-kubernetes-endpoints-port: 80

  cfapi-admin-svc: cfapi-admin
  cfapi-admin-port: 80

  cfapi-teams-svc: cfapi-teams
  cfapi-teams-port: 80

  cfapi-ws-svc: cfapi-ws
  cfapi-ws-port: 80

  cfui-svc: cfui
  cfui-port: 80

  argo-platform-namespace: codefresh-v2
  argo-platform-api-graphql-svc: argo-platform-api-graphql
  argo-platform-api-graphql-port: 80
  argo-platform-api-events-svc: argo-platform-api-events
  argo-platform-api-events-port: 80
  argo-platform-ui-svc: argo-platform-ui
  argo-platform-ui-port: 4200

## See full values structure at https://github.com/codefresh-io/helm-charts/blob/master/charts/cf-common/values.yaml
# -- Global parameters
# @default -- See below
global:
  # -- configures cluster domain ("cluster.local" by default)
  clusterDomain: "cluster.local"
  # -- configures DNS service name
  dnsService: "kube-dns"
  # -- configures DNS service namespace
  dnsNamespace: "kube-system"

# -- Ingress parameters
# @default -- See below
ingress:
  main:
    enabled: false
    ingressClassName: "nginx-codefresh"
    hosts:
      - host: '{{ regexReplaceAll "^https?://" .Values.codefresh.url "" }}'
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            service:
              name: '{{ include "internal-gateway.fullname" . }}'
              port: "{{ .Values.service.main.ports.http.port }}"

nginx:
  config:
    # -- Enable logging of 2xx and 3xx HTTP requests
    verboseLogging: true
    # -- NGINX log format
    logFormat: |-
      main '$remote_addr - $remote_user [$time_local]  $status '
              '"$request" $body_bytes_sent "$http_referer" '
              '"$http_user_agent" "$http_x_forwarded_for"';
    # -- Sets the log level of the NGINX error log. One of `debug`, `info`, `notice`, `warn`, `error`, `crit`, `alert`, or `emerg`
    errorLogLevel: error
    # -- Enables NGINX access logs
    accessLogEnabled: true
    # -- Allows appending custom configuration to the server block
    serverSnippet: ""
    # -- Allows appending custom configuration to the http block
    httpSnippet: ""
    # -- Allows to set a custom resolver
    resolver: null

    # -- Description
    workerProcesses: 5
    workerConnections: 4096

    # -- Set proxy parameters
    # Ref: https://nginx.org/en/docs/http/ngx_http_proxy_module.html
    proxyConf:
      proxy_buffer_size: "64k"
      proxy_buffers: "4 64k"
      client_max_body_size: "5M"
      client_body_buffer_size: "16k"
      proxy_connect_timeout: "5s"
      proxy_send_timeout: "60s"
      proxy_read_timeout: "60s"

    # -- Config file contents for Nginx. Passed through the `tpl` function to allow templating.
    # !! Moved into separate template at `templates/nginx/configmap.yaml`
    # @default -- See below
    file: ""

# -- Controller parameters
# @default -- See below
controller:
  enabled: true
  type: deployment
  replicas: 2
  deployment:
    strategy: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: "50%"

# -- Pod annotations
# @default -- See below
podAnnotations:
  checksum/config: '{{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}'

# -- Pod Security Context parameters
# @default -- See below
podSecurityContext:
  fsGroup: 101
  runAsGroup: 101
  runAsNonRoot: true
  runAsUser: 101

# -- Main container parameters
# @default -- See below
container:
  image:
    registry: docker.io
    repository: nginxinc/nginx-unprivileged
    tag: 1.23-alpine

  env: {}
  envFrom: []

  volumeMounts:
    config:
      path:
        - mountPath: /etc/nginx

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 2Gi

  probes:
    readiness:
      enabled: true
      type: httpGet
      httpGet:
        path: /ready
        port: http
      spec:
        initialDelaySeconds: 15
        timeoutSeconds: 3
        periodSeconds: 5
        failureThreshold: 3
        successThreshold: 1
    liveness:
      enabled: true
      type: httpGet
      httpGet:
        path: /
        port: http
      spec:
        initialDelaySeconds: 30
        timeoutSeconds: 3
        periodSeconds: 5
        failureThreshold: 3
        successThreshold: 1

# -- Container security context parameters
# @default -- See below
containerSecurityContext:
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false

# -- Service parameters
# @default -- See below
service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        port: 80
        protocol: HTTP
        targetPort: 8080

# -- Volumes parameters
# @default -- See below
volumes:
  config:
    enabled: true
    type: configMap

# -- HPA parameters
# @default -- See below
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetMemoryUtilizationPercentage: 70
  targetCPUUtilizationPercentage: 70

# -- PDB parameters
# @default -- See below
pdb:
  enabled: false
  minAvailable: "50%"

# -- Topologe Spread Constraints parameters
# @default -- See below
topologySpreadConstraints: |
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        {{- include "internal-gateway.selectorLabels" . | nindent 6 }}
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        {{- include "internal-gateway.selectorLabels" . | nindent 6 }}

# -- Service Account parameters
# @default -- See below
serviceAccount:
  enabled: false

# -- RBAC parameters
# @default -- See below
rbac:
  enabled: false
