{{- define "internal-gateway.resources" -}}

{{ include "internal-gateway.deployment" . }}
---
{{ include "internal-gateway.ingress" .}}
---
{{ include "internal-gateway.configmap" . }}
---
{{ include "internal-gateway.rbac" . }}
---
{{ include "internal-gateway.service" . }}
---
{{ include "internal-gateway.hpa" . }}
---
{{ include "internal-gateway.pdb" . }}

{{- end -}}
