{{- if not .Values.libraryMode }}
{{- $vals := include "internal-gateway.default-values" . | fromYaml }}
{{- $context := deepCopy . }}
{{- $mergedValues := mergeOverwrite $vals .Values }}
{{- $_ := set $context "Values" $mergedValues }}
{{- include "internal-gateway.configmap" $context }}
{{- end }}
