{{- define "my-values" }}
codefresh:
  serviceEndpoints:
    cfapi-endpoints:
      svc: '{{ .Release.Name }}-{{ index .Values.codefresh "cfapi-endpoints-svc" }}'
      port: 8080
nginx:
  config:
    workerConnections: "666"
{{- end }}

{{- if not .Values.libraryMode }}
{{- $vals := include "my-values" . | fromYaml }}
{{- $context := deepCopy . }}
{{- $mergedValues := mergeOverwrite .Values $vals }}
{{- $_ := set $context "Values" $mergedValues }}
{{- include "internal-gateway.configmap-new" $context }}
{{- end }}
