apiVersion: v2
name: mongodb
description: MongoDB database Helm chart
version: 0.1.1
appVersion: "7.0"
type: application
keywords:
  - mongodb
  - database
  - nosql
home: https://codefresh.io/
maintainers:
  - name: codefresh
    url: https://codefresh-io.github.io/
dependencies:
  - name: cf-common
    repository: oci://quay.io/codefresh/charts/dev
    version: "0.32.0"
