apiVersion: v2
description: Helm Chart for Launch-Composition Runner (onprem)
name: runner
version: 1.3.0
keywords:
- codefresh
- dind
- runner
home: https://codefresh.io/
icon: https://avatars1.githubusercontent.com/u/11412079?v=3
maintainers:
  - name: codefresh
    url: https://codefresh-io.github.io/
dependencies:
  - name: cf-common
    repository: oci://quay.io/codefresh/charts
    version: "0.23.0"
