# -- Global parameters
global:
  # -- Global Docker image registry
  imageRegistry: ""
  # -- Global Docker registry secret names as array
  imagePullSecrets: []
  # E.g.
  # imagePullSecrets:
  #   - myRegistrySecret
  # Global controller parameters
  controller:
    # -- Define the controller type (`deployment` \ `rollout`)
    type: ""
    # Deployment parameters (overrides for global.deployment values)
    deployment:
      # -- Set deployment upgrade strategy (`RollingUpdate`/`Recreate`)
      strategy:
      # RollingUpdate strategy parameters
      rollingUpdate:
        # -- Set RollingUpdate max unavailable (absolute number or percentage)
        maxUnavailable:
        # -- Set RollingUpdate max surge (absolute number or percentage)
        maxSurge:
    # Global Rollout parameters
    rollout:
      # Analysis template parameters to run in the background during a rollout update.
      analysisTemplate:
        # Enable analysis template
        enabled:
        # Array of arguments to pass
        args:
        # The metrics which the analysis should perform
        metrics:
            # The name of the metric
          - name:
            # The maximum number of failed run an analysis is allowed.
            failureLimit:
            # Determines if a measurement is considered failed
            failureCondition:
            # Determines if a measurement is considered successful
            successCondition:
            # The external metrics system to use to verify the analysis
            provider:
              # Defines NewRelic as the external metrics system
              newRelic:
                # The name of the secret holding NewRelic account configuration
                profile:
                # A raw NewRelic NRQL query to perform
                query:
      # Analysis history configuration
      analysis:
        # Limits the number of successful analysis runs and experiments to be stored in a history
        successfulRunHistoryLimit:
        # Limits the number of unsuccessful analysis runs and experiments to be stored in a history. ( Stages for unsuccessful: "Error", "Failed", "Inconclusive" )
        unsuccessfulRunHistoryLimit:
      # Rollout update strategy - can be Canary or BlueGreen.
      strategy:
      # Canary update strategy parameters
      canary:
        # The maximum number of pods that can be unavailable during the update. Value can be an absolute number / percentage
        maxUnavailable:
        # The maximum number of pods that can be scheduled above the original number of pods. Value can be an absolute number / percentage
        maxSurge:
        # Steps define sequence of steps to take during an update of the canary.
        steps:
          # Sets the ratio of canary ReplicaSet in percentage.
          - setWeight:
          # Pauses the rollout for configured duration of time. Supported units: s, m, h. when setting `duration: {}` it will pauses indefinitely until manually resumed
          - pause:
              duration:
          - setWeight:
          - pause:
              duration:
  # -- Global Env vars. NO precedence over `.Values.container.env`
  env: {}

# -- Controller parameters
# @default -- See below
controller:
  # -- Define the controller type (`deployment`/`rollout`/`job`)
  type: ""
  # -- Set labels on controller
  labels: {}
  # -- Set annotations on controller
  annotations: {}
  # -- Override the name suffix that is used for this controller
  nameOverride: ""
  # -- Set number of pods
  replicas:
  # -- Set ReplicaSet revision history limit
  revisionHistoryLimit:
  # Deployment parameters (overrides for global.deployment values)
  deployment:
    # -- Set deployment upgrade strategy (`RollingUpdate`/`Recreate`)
    strategy:
    # RollingUpdate strategy parameters
    rollingUpdate:
      # -- Set RollingUpdate max unavailable (absolute number or percentage)
      maxUnavailable:
      # -- Set RollingUpdate max surge (absolute number or percentage)
      maxSurge:
  # Rollout parameters (overrides for global.rollout values)
  rollout:
    # Analysis template parameters to run in the background during a rollout update.
    analysisTemplate:
      # Enable analysis template
      enabled:
      # Array of arguments to pass
      args:
      # The metrics which the analysis should perform
      metrics:
          # The name of the metric
        - name:
          # The maximum number of failed run an analysis is allowed.
          failureLimit:
          # Determines if a measurement is considered failed
          failureCondition:
          # Determines if a measurement is considered successful
          successCondition:
          # The external metrics system to use to verify the analysis
          provider:
            # Defines NewRelic as the external metrics system
            newRelic:
              # The name of the secret holding NewRelic account configuration
              profile:
              # A raw NewRelic NRQL query to perform
              query:
    # Analysis history configuration
    analysis:
      # -- Limits the number of successful analysis runs and experiments to be stored in a history
      successfulRunHistoryLimit:
      # -- Limits the number of unsuccessful analysis runs and experiments to be stored in a history. ( Stages for unsuccessful: "Error", "Failed", "Inconclusive" )
      unsuccessfulRunHistoryLimit:
    # -- Rollout update strategy - can be Canary or BlueGreen.
    strategy:
    # -- Canary update strategy parameters
    canary:
      # -- The maximum number of pods that can be unavailable during the update. Value can be an absolute number / percentage
      maxUnavailable:
      # -- The maximum number of pods that can be scheduled above the original number of pods. Value can be an absolute number / percentage
      maxSurge:
      # -- Steps define sequence of steps to take during an update of the canary.
      steps:
        # -- Sets the ratio of canary ReplicaSet in percentage.
        - setWeight:
        # -- Pauses the rollout for configured duration of time. Supported units: s, m, h. when setting `duration: {}` it will pauses indefinitely until manually resumed
        - pause:
            duration:
        - setWeight:
        - pause:
            duration:
  # Job parameters
  job:
    # -- Set the duration in seconds relative to the startTime that the job may be continuously active before the system tries to terminate it; value must be positive integer. (int)
    activeDeadlineSeconds:
    # -- Set the number of retries before marking this job failed. Defaults to 6. (int)
    backoffLimit:
    # -- Set the desired number of successfully finished pods the job should be run with. (int)
    completions:
    # -- Controls generation of pod labels and pod selectors. Leave manualSelector unset unless you are certain what you are doing. (boolean)
    # Ref: https://kubernetes.io/docs/concepts/workloads/controllers/job/#specifying-your-own-pod-selector
    manualSelector:
    # -- A label query over pods that should match the pod count. Normally, the system sets this field for you.
    # Ref: https://kubernetes.io/docs/concepts/workloads/controllers/job/#specifying-your-own-pod-selector
    selector:
    # -- Set the maximum desired number of pods the job should run at any given time. (int)
    parallelism:
    # -- Suspend specifies whether the Job controller should create Pods or not. (boolean)
    suspend:
    # -- Set the limit on the lifetime of a Job that has finished execution (either Complete or Failed). (int)
    ttlSecondsAfterFinished:

# -- Set image pull secrets as array
imagePullSecrets: []
# E.g.
# imagePullSecrets:
#   - myRegistrySecret

# -- Set additional pod labels
podLabels: {}
# -- Set additional pod annotations
podAnnotations: {}

# -- Duration in seconds the pod needs to terminate gracefully
terminationGracePeriodSeconds:

# -- Main Container parameters
# @default -- See below
container:
  # -- Image parameters
  image:
    # -- Set image registry
    registry:
    # -- Set image repository
    repository:
    # -- Set image tag
    tag:
    # -- Set image pull policy (`Always`, `Never`, `IfNotPresent`)
    pullPolicy:

  # -- Override commands for the container
  command: []
  # -- Override args for the container
  args: []

  # -- Set environments variables. Helm template supported.
  env: {}
  # E.g.
  # env:
  #   ALICE: BOB
  #   FOO: "{{ .Valies.config.foo }}"
  # -- Set Secrets or ConfigMaps loaded as environment variables.
  envFrom: []
  # E.g.
  # envFrom:
  #   - secretRef:
  #       name: my-secret
  #   - configMapRef:
  #       name: my-config-map

  # -- Set volume mounts for container
  volumeMounts: {}

  # Volume Mount name should match the Volume name (see `volumes` and `externalVolumes` section)
  # E.g.
  # volumeMounts:
  #   config:
  #     path:
  #     - mountPath: /some/path/config.json
  #       subPath: config.json
  #   secret:
  #     path:
  #     - mountPath: /some/path/private.key
  #       subPath: private.key
  #       readOnly: true
  #   data:
  #     path:
  #     - mountPath: /var/www/html

  # Probes configuration
  probes:
    # Liveness probe configuration
    liveness:
      # -- Enable liveness probe
      enabled: false
      # -- Set liveness probe type (httpGet/exec)
      type:
      # httpGet probe type parameters
      httpGet:
        # -- Set httpGet probe path
        path:
        # -- Set httpGet probe port (name )
        port:
      # exec probe type parameters
      exec:
        # -- Set exec probe commands
        command: []
      # Liveness probe spec
      spec:
        # -- Set initial delay seconds for probe
        initialDelaySeconds:
        # -- Set period seconds for probe
        periodSeconds:
        # -- Set timeout seconds for probe
        timeoutSeconds:
        # -- Set success threshold for probe
        successThreshold:
        # -- Set failure threshold for probe
        failureThreshold:
    # Readiness probe configuration (parameters are identical to liveness)
    readiness:
      enabled: false
    # Startup probe configuration (parameters are identical to liveness)
    startup:
      enabled: false

  # -- Set the resources (requests/limits) for the container
  resources:
    limits: {}
    requests: {}
  # E.g.
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi

  # -- Set security context for container
  containerSecurityContext: {}
  # Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  # E.g.
  # containerSecurityContext:
  #   allowPrivilegeEscalation: false

  # -- Set the lifecycle hooks for container
  lifecycle: {}
  # Ref: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
  # E.g.
  # lifecycle:
  #   preStop:
  #     exec:
  #       command:
  #       - sh
  #       - -c
  #       - "sleep 5"

# Create secrets with the values you provide.
# Additional Secrets can be added by adding a dictionary key similar to the 'secret' object.
# @default -- See below
secrets:
  # -- Secret name. Make sure to use the same name in `volumes` and `container.volumeMounts`
  secret:
    # -- Enable the secret
    enabled: false
    # -- Add additional labels to the secret
    labels: {}
    # -- Add additional annotations to the secret
    annotation: {}
    # -- Set secret type (`Opaque`/`kubernetes.io/tls`)
    type: Opaque
    # -- Secret data content. Plain text (not base64). Helm template supported. Passed through `tpl`, should be configured as string
    stringData: {}
    # stringData:
    #   FOO: BAR
    # E.g.
    # stringData: |
    #   FOO: "{{ .Values.global.foo }}"
    #   BAR: "{{ .Values.global.bar }}"
    #   {{- if .Values.global.something }}
    #   ALICE: value
    #   {{- end }}
    data: {}
    # -- Secret data content. Should be passed as base64 encoded text
    # Helm template NOT supported.
    # E.g.
    # data:
    #   tls.crt: |
    #         MIIC2DCCAcCgAwIBAgIBATANBgkqh ...
    #   tls.key: |
    #         MIIEpgIBAAKCAQEA7yn3bRHQ5FHMQ ...

# -- Create configMap with the values you provide.
# Additional configMaps can be added by adding a dictionary key similar to the 'config' object.
# @default -- See below
configMaps:
  # -- ConfigMap name. Make sure to use the same name in `volumes` and `container.volumeMounts`
  config:
    # -- Enable the configMap
    enabled: false
    # -- Add additional labels to the configMap
    labels: {}
    # -- Add additional annotations to the configMap
    annotations: {}
    # -- ConfigMap data content.
    data: {}
      # foo: bar
    # Helm template supported. Passed through `tpl`, should be configured as string
    # E.g.
    # data: |
    #   ALICE: "{{ .Values.global.alice }}"
    #   BOB: "{{ .Values.global.bob }}"

# -- Configure volume for the controller.
# Additional items can be added by adding a dictionary key similar to the 'config'/`secret` key.
# @default -- See below
volumes:
  # -- Volume name. Make sure to use the same name in `configMaps`/`secrets` and `container.volumeMounts`
  config:
    # -- Enable the volume
    enabled: false
    # -- Volume type (configMap/secret)
    type: configMap
  secret:
    enabled: false
    type: secret
  # Configure existing volumes (from other/parent chart) for the contoller.
  # Make sure to specify `existingName` property. Helm template supported.
  # E.g.
  # volumes:
  #   dind-clusters:
  #     enabled: true
  #     type: secret
  #     existingName: "{{ .Values.config.dindClustersSecretName }}"
  #     optional: true

# -- Configure services fo the chart.
# Additional services can be added by adding a dictionary key similar to the 'main' service.
# @default -- See below
service:
  # -- Service name
  main:
    # -- Enabled the service
    enabled: false
    # -- Make this the primary service (used in probes, notes, etc...).
    # If there is more than 1 service, make sure that only 1 service is marked as primary.
    primary: true
    # -- Add additional labels for the service
    labels: {}
    # -- Add additional annotations for the service
    annotations: {}
    # -- Set the service type
    type: ClusterIP
    # -- Allow adding additional match labels
    extraSelectorLabels: {}
    # -- Configure ports for the service
    ports:
      # Additional ports can be added by adding a dictionary key similar to the 'http' service.
      # -- Port name
      http:
        # -- Port number
        port:
        # -- Port protocol (`HTTP`/`HTTPS`/`TCP`/`UDP`)
        protocol: HTTP
        # -- Set a service targetPort if you wish to differ the service port from the application port.
        targetPort:
        # If `targetPort` is specified, this port number is used in the container definition instead of
        # the `port` value. Therefore named ports are not supported for this field

# -- Configure the Ingresses for the chart.
# Additional Ingresses can be added by adding a dictionary key similar to the 'main' ingress.
# @default -- See below
ingress:
  main:
    # -- Enables or disables the ingress
    enabled: false
    # -- Add additional labels for ingress.
    labels: {}
    # -- Add additional annotations for ingress.
    annotations: {}
    # E.g.
    # annotations:
    #   kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: "true"
    # -- Set the ingressClass that is used for the ingress.
    ingressClassName:  # "nginx"

    ## -- Configure the hosts for the ingress
    hosts:
      -  # -- Host address. Helm template can be passed.
        host: domain.example.com
        ## - Configure the paths for the host
        paths:
          -  # -- Path. Helm template can be passed.
            path: /
            # -- Path Type (`Prefix`/`ImplementationSpecific`(default)/`Exact`)
            pathType:
            service:
              # -- Set the service name reference for this path. Helm template can be passed.
              name:
              # -- Set the service port reference for this path. Helm template can be passed.
              port:

    # -- Configure TLS for the ingress. Both secretName and hosts can process a Helm template.
    tls: []
    #  - secretName: domain-example-tls
    #    hosts:
    #      - domain.example.com

# -- Specifies whether a service account token should be automatically mounted.
automountServiceAccountToken: true

# -- Set security context for the pod
podSecurityContext: {}
# E.g.
# podSecurityContext:
#   runAsNonRoot: true
#   runAsGroup: 0
#   fsGroup: 0
#   runAsUser: 1000

# -- Set node selection constrains
nodeSelector: {}

# -- Set tolerations constrains
tolerations: []

# -- Set affinity constrains
affinity: {}

# -- Set topologySpreadConstraints rules.
# Helm template supported. Passed through `tpl`, should be configured as string
topologySpreadConstraints: []
# E.g.
# topologySpreadConstraints: |
#   - maxSkew: 1
#     topologyKey: topology.kubernetes.io/zone
#     whenUnsatisfiable: ScheduleAnyway
#     labelSelector:
#       matchLabels:
#         {{- include "cf-common.labels.matchLabels" . | nindent 6 }}

# -- Configure autoscaling (Horizontal Pod Autoscaler)
# @default -- See below
hpa:
  # -- Enable HPA
  enabled: false
  # -- Set minimum autoscaling replicas
  minReplicas:
  # -- Set maximum autoscaling replicas
  maxReplicas:
  # -- Set target CPU utilization percentage
  targetCPUUtilizationPercentage:
  # -- Set custom metrics
  metrics: []
  # E.g.
  # metrics:
  #   - type: Object
  #   object:
  #     metric:
  #       name: requests_per_pod
  #     describedObject:
  #       apiVersion: "v1"
  #       kind: Service
  #       name: production-cfapi-endpoints
  #     target:
  #       type: Value
  #       value: 7

# -- Configure Pod Disruption Budget
# @default -- See below
pdb:
  # -- Enable PDB
  enabled: false
  # -- Set number of pods that are available after eviction as number of percentage
  minAvailable: ""
  # -- Set number of pods that are unavailable after eviction as number of percentage
  maxUnavailable: ""

# -- Configure Service Account
# @default -- See below
serviceAccount:
  # -- Enable and create Service Account
  enabled: false
  # -- Override Service Account name (by default, name is generated with `fullname` template)
  nameOverride: ""
  # -- Set annotations for Service Account
  annotations: {}

# -- Configure RBAC parameters
# @default -- See below
rbac:
  # -- Enable RBAC resources
  enabled: false
  # -- Create custom rules
  rules: []
  # E.g.
  # rules:
  #   - apiGroups:
  #       - ""
  #     resources:
  #       - pods
  #     verbs:
  #       - get
  #       - list
  #       - watch
  #       - update

# -- Array of extra objects to deploy with the release
extraResources: []
# E.g.
# extraResources:
# - apiVersion: v1
#   kind: Pod
#   metadata:
#     name: dnsutils
#     namespace: default
#   spec:
#     containers:
#     - name: dnsutils
#       image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
#       command:
#         - sleep
#         - "infinity"
#       imagePullPolicy: IfNotPresent
#     restartPolicy: Always

# -- Array of init containers to add
initContainers: []
# E.g.
# initContainers:
#   - name: init-myservice
#     image: busybox:1.28
#     command: ['sh', '-c', "sleep 60"]

# -- Array of extra (sidecar) containers to add
additionalContainers: []
# E.g.
# additionalContainers:
#   - name: sidecar-container
#     image: busybox
#     command: ["/bin/sh"]
#     args: ["-c", "while true; do echo echo $(date -u) 'Hi I am from Sidecar container' >> /var/log/index.html; sleep 5;done"]
#     resources: {}
#     volumeMounts:
#     - name: var-logs
#       mountPath: /var/log
