apiVersion: v2
name: cf-vcluster
description: Umbrella chart over vCluster adjusted for Codefresh use cases - mainly in Crossplane compositions
type: application
version: 0.28.0-0
appVersion: "0.28.0"
dependencies:
  - name: vcluster
    version: 0.28.0
maintainers:
  - name: codefresh
    url: https://codefresh-io.github.io/
