# Test values file to deploy on rnd-sandbox vcluster host
global:
  ingress:
    internal:
      enabled: true
      className: nginx-internal
      host:
        domain: vclusters.rnd-sandbox.cf-infra.com
  monitoring:
    monitoredNamespaces: ["test-ns"]
    additionalResourceAttributes:
      team: rnd
automaticScaleDown:
  enabled: false
  periodSeconds: 60
