fullnameOverride: postgresql

auth:
  username: postgres
  password: password
  database: ""

config:
  listen_addresses: "'*'"
  port: 5432
  shared_preload_libraries: "'pg_partman_bgw, pg_cron'"
  pg_cron.database: "'postgres'"
  pg_partman_bgw.dbname: "'postgres'"
  pg_partman_bgw.interval: 3600

global: {}

controller:
  enabled: true
  type: statefulset
  replicas: 1
  podManagementPolicy: OrderedReady

container:
  image:
    registry: quay.io
    repository: codefresh/postgresql
    tag: 17.6-featvanilla-postgresql
    pullPolicy: IfNotPresent

  args:
    - "-c"
    - "config_file=/etc/postgresql/postgresql.conf"

  env:
    PGDATA: /var/lib/postgresql/data/pgdata

  probes:
    liveness:
      enabled: true
      type: exec
      exec:
        command:
          - pg_isready
          - -U
          - postgres
      spec:
        initialDelaySeconds: 30
        periodSeconds: 20
        timeoutSeconds: 10
        successThreshold: 1
        failureThreshold: 6
    readiness:
      enabled: true
      type: exec
      exec:
        command:
          - pg_isready
          - -U
          - postgres
      spec:
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 6

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  volumeMounts:
    config:
      path:
        - mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf

volumeClaimTemplates:
  data:
    mountPath: /var/lib/postgresql/data
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass:

secrets:
  secret:
    enabled: true
    stringData: |
      POSTGRES_USER: "{{ .Values.auth.username }}"
      POSTGRES_PASSWORD: "{{ required ".Values.auth.password is required" .Values.auth.password }}"
      {{- if .Values.auth.database }}
      POSTGRES_DB: "{{ .Values.auth.database }}"
      {{- end }}

configMaps:
  config:
    enabled: true
    data:
      postgresql.conf: |
       {{- range $key, $value := .Values.config }}
       {{ $key }} = {{ $value }}
       {{- end }}


volumes:
  config:
    enabled: true
    type: configMap

service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      postgresql:
        port: 5432
        protocol: TCP

podSecurityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
