## Reference: https://github.com/helm/chart-releaser-action
name: Publish Charts
on:
  push:
    branches:
      - master
    paths:
      - "charts/**"

concurrency:
  group: helm-release

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Upload charts to quay.io
        run: |
          set -o xtrace
          helm registry login quay.io -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }}
          if [ -d .cr-release-packages ]; then
            for CHART in $(find .cr-release-packages -type f -printf '%f\n'); do
              CHART_NAME=$(echo $CHART | rev | cut -d '-' -f2- | rev )
              helm push .cr-release-packages/$CHART oci://quay.io/codefresh/charts
            done
          fi
